### PR TITLE
added login form

### PR DESCRIPTION
**Pull request by ShravaniAK**

### CODE REVIEW

**Comment by killerraj369** [comment]
Please attach a screenshot of your work

**Comment by ShravaniAK** [comment]
Screenshot 2022-10-12 at 11 04 21 AM

**Comment by killerraj369** [comment]
Hey @ShravaniAK ,
Can you please add a sign up form if interested.
I will then merge your PR

**Comment by killerraj369** [comment]
This branch has conflicts that must be resolved. Resolve Conflicts.
You have to fork again and then make the changes

**Pull request closed without merging**
