### PR TITLE
logo

### PR DESCRIPTION
**Pull request by aakash1233333**

### CODE REVIEW

**Comment by aakash1233333** [comment]
I want to push 3 commits just please check it ! And please merge it !
Thanks

**Comment by killerraj369** [comment]
This branch has conflicts that must be resolved
I am closing this pull request. Make a new fork and then change the logo with a good one. 
I will definitely merge it then

**Comment by aakash1233333** [comment]
I have resolved the issue if you are saying I may do it again with new logo
.

**Comment by aakash1233333** [comment]
Now please check
Thanks for answering my query really appreciate it

**Comment by aakash1233333** [comment]
Now please check all the conflicts resolved added 5 new commits

**Comment by aakash1233333** [comment]
Please check it soon and tell me

**Pull request closed without merging**
