### PR TITLE
Light/Dark Mode Toggle Button 

### PR DESCRIPTION
**Pull request by ghost**
Toggle at the bottom left corner of the pages that allows to switch between dark and light mode- theotsuaneng

### CODE REVIEW

**Comment by ghost** [comment]
@killerraj369 Hi can you please accept my pull PR #57

**Comment by killerraj369** [comment]
Hey @theotsuaneng , Can you please add Light/Dark Mode button in the Navbar and not in the footer.
Also please confirm your changes from the Preview.

**Comment by ghost** [comment]
@killerraj369 Hi I have resolved the issue and removed the toggle from the footer.
The two photos show the home page with the mode button in dark and light mode. 
The issue is PR #57 
Screenshot (64)

Screenshot (63)

**Comment by ghost** [comment]
@killerraj369 hello may you kindly accept my pull, i have completed the work. I am doing this for an assignment for my university this would be greatly be appreciated.

**Comment by killerraj369** [comment]
Ok, Merging then

**Pull request merged**
