### PR TITLE
Added hovering resume templates

### PR DESCRIPTION
**Pull request by pranavsuriya-sr**
Added some hovering effects to the resume templates. 

https://user-images.githubusercontent.com/91081814/195631211-69b52caa-afa4-4649-8801-de1ab25902c2.mp4

### CODE REVIEW

**Comment by killerraj369** [comment]
Make cursor pointer when hovering over the resumes.
Also add different resumes. I will then merge your PR

**Comment by pranavsuriya-sr** [comment]
I will add the cursor pointer while hovering. But the resumes are the ones which were already there on the site. I didn't add them. I just made the effects. I will do the changes required.

**Comment by pranavsuriya-sr** [comment]
Added cursor pointer while hovering and added different resume templates.  

https://user-images.githubusercontent.com/91081814/195662430-23147477-9a24-4180-9da9-702a49fc0c41.mp4

**Comment by pranavsuriya-sr** [comment]
Please review my pr.

**Comment by killerraj369** [comment]
I cann't see the Navigate to top button in the preview.
Also Please add good looking resumes

**Comment by pranavsuriya-sr** [comment]
Its visible for me. Please check the deployment link. 

https://resume-maker-f02q41b9q-killerraj369.vercel.app/

The button will appear only if you scroll down a bit from the main page.   

Regarding the resume template part I will try to find some better pics. But it would be great if you can assign it for no code developers.

**Comment by killerraj369** [comment]
Ok then.

**Pull request merged**
